import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Common standards',
      items: [
        'standards/using-git',
        'standards/storing-source-code',
      ]
    },
    {
      type: 'category',
      label: 'Backend',
      items: [
        'backend/code-quality',
        'backend/code-review',
      ]
    },
    {
      type: 'category',
      label: 'Frontend',
      items: [
        'frontend/code-quality',
        'frontend/code-review',
        'frontend/fe-accessibility',
        'frontend/internal-dependencies',
        'frontend/languages-and-frameworks',
        'frontend/local-development',
        'frontend/testing',
        'frontend/third-party-dependencies',
      ]
    },
  ]
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
